host = 'pro.ambicam.com'; // hostname or IP address
//host = '127.0.0.1'
port = 9001;
dbName = "vmukti";
tbName = "VCam1_1";
topic = 'hr-0002'; 	// topic to subscribe to
useTLS = false;
username = null;
password = null;
// username = "jjolie";
// password = "aa";
ourQos = 0;
cleansession = true;
updateTime = 30000;
reconnectTimeout = 2000;