name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build with dotnet
        run: dotnet build
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: testaspdotnet1
          publish-profile: ${{ secrets.<publishData><publishProfile profileName="testaspdotnet1 - Web Deploy" publishMethod="MSDeploy" publishUrl="testaspdotnet1.scm.azurewebsites.net:443" msdeploySite="testaspdotnet1" userName="$testaspdotnet1" userPWD="h3Xno6pllXio5RXcT9q5ida6inxKfhR7YworqtAg0hDdmSQ9THsoZBeagenp" destinationAppUrl="https://testaspdotnet1.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="testaspdotnet1 - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-pn1-009.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="testaspdotnet1\$testaspdotnet1" userPWD="h3Xno6pllXio5RXcT9q5ida6inxKfhR7YworqtAg0hDdmSQ9THsoZBeagenp" destinationAppUrl="https://testaspdotnet1.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="testaspdotnet1 - Zip Deploy" publishMethod="ZipDeploy" publishUrl="testaspdotnet1.scm.azurewebsites.net:443" userName="$testaspdotnet1" userPWD="h3Xno6pllXio5RXcT9q5ida6inxKfhR7YworqtAg0hDdmSQ9THsoZBeagenp" destinationAppUrl="https://testaspdotnet1.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData> }}
          package: ./bin/Release/*.zip
