name: ASP.NET Build and Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: 🚀 Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.418'

    - name: 💼 Publish ASP.NET project
      run: msbuild /p:Configuration=Release /p:OutputPath=WebApp

    - name: 📂 Sync files to Azure Web App via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        local-dir: 'WebApp/'
        remote-dir: '/site/wwwroot'
