name: Build and deploy ASP app to Azure Web App - aspdotnettestapp1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore WebApp/exam.sln

      - name: List contents of /published directory
        run: ls -R /published

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: https://aspdotnettestapp1.azurewebsites.net/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore WebApp/exam.sln

      - name: Install IIS
        run: |
          Install-WindowsFeature -Name Web-Server -IncludeManagementTools


      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with: 
          app-name: 'aspdotnettestapp1'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AF40BF76CFD842D89CD6B30A431D4412  }}
          package: .
